dist: trusty
sudo: required

language: node_js
node_js:
  - "8"
  
addons:
    chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install
  
script:
  - ng lint
  - ng build core --prod
  - ng build interface --prod
  - ng build --prod
  - ng test core --code-coverage --watch=false --browsers ChromeHeadless
  - ng test interface --code-coverage --watch=false --browsers ChromeHeadless